name: scrolly
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.7.0
  cupertino_icons: ^1.0.0
  auth_buttons: ^0.0.4
  firebase_auth: ^0.20.0
  provider: ^4.3.3
  google_sign_in: ^4.5.9
  cloud_firestore: ^0.16.0
  firebase_messaging: 
  firebase_storage: ^7.0.0
  # path_provider: ^1.6.27
  google_nav_bar: ^3.2.0
  image_picker: ^0.6.7+22
  flutter_svg: ^0.19.1
  image_cropper: ^1.3.1 # And you too. Just e doing anyhow oo
  shimmer: ^1.1.2
  image_crop: ^0.3.4 # i neva get your time oo. I am coming
  intl: ^0.16.1
  pull_to_refresh: ^1.6.3
  chat_ui_kit: ^1.1.2
  image_picker_gallery_camera: ^0.1.6
  flutter_speed_dial: ^1.2.5
  flutter_sound: ^7.5.3+1
  shared_preferences: 
  flutter_local_notifications:
  fluttertoast: 
  multi_image_picker:
  permission_handler_platform_interface: ^2.0.1
  photo_view: 
  rflutter_alert:
  after_layout: ^1.0.7+2
  emoji_picker: ^0.1.0
  loading_indicator: ^1.2.0
  animations: ^1.1.2
  auto_size_text: ^2.1.0
  progressive_image: ^1.0.1
  cached_network_image: ^2.0.0
  permission_handler: ^5.0.1+1
  google_fonts: ^1.1.1
  blurrycontainer: ^0.0.1
  flutter_switch: ^0.2.0
  geolocator: ^6.1.14
  geocoding: ^1.0.5
  linkwell: ^0.1.9
  url_launcher: ^5.7.10
  like_button: ^1.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-LightItalic.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
